### ISSUE TITLE
Querying with username starting with underscore causes org.elasticsearch.indices.InvalidIndexNameException

### ISSUE THREAD

**Issue by robmartin-scibite** [opendistro-for-elasticsearch/sample-code#245]
When I run a query with an JWT token containing a username starting with an underscore, the following exception is thrown:
```
org.elasticsearch.indices.InvalidIndexNameException: Invalid index name [_d0tmzjxzlwzeyecsdg8qgum4hhafpvgwt3dyp8_k], must not start with '_'.
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.validateAliasOrIndex(IndexNameExpressionResolver.java:859) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.innerResolve(IndexNameExpressionResolver.java:796) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.resolve(IndexNameExpressionResolver.java:775) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:191) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:171) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:103) ~[elasticsearch-7.9.1.jar:7.9.1]
	at com.amazon.opendistroforelasticsearch.security.securityconf.ConfigModelV7$IndexPattern.getResolvedIndexPattern(ConfigModelV7.java:760) ~[opendistro_security-1.10.1.0.jar:1.10.1.0]
	at com.amazon.opendistroforelasticsearch.security.securityconf.ConfigModelV7$IndexPattern.access$400(ConfigModelV7.java:644) ~[opendistro_security-1.10.1.0.jar:1.10.1.0]
	at com.amazon.opendistroforelasticsearch.security.securityconf.ConfigModelV7.lambda$impliesTypePerm$1(ConfigModelV7.java:958) ~[opendistro_security-1.10.1.0.jar:1.10.1.0]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.securityconf.ConfigModelV7.impliesTypePerm(ConfigModelV7.java:959) ~[opendistro_security-1.10.1.0.jar:1.10.1.0]
	at com.amazon.opendistroforelasticsearch.security.securityconf.ConfigModelV7.access$600(ConfigModelV7.java:69) ~[opendistro_security-1.10.1.0.jar:1.10.1.0]
	at com.amazon.opendistroforelasticsearch.security.securityconf.ConfigModelV7$SecurityRoles.impliesTypePermGlobal(ConfigModelV7.java:488) ~[opendistro_security-1.10.1.0.jar:1.10.1.0]
	at com.amazon.opendistroforelasticsearch.security.privileges.PrivilegesEvaluator.evaluate(PrivilegesEvaluator.java:419) ~[opendistro_security-1.10.1.0.jar:1.10.1.0]
	at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityFilter.apply0(OpenDistroSecurityFilter.java:274) [opendistro_security-1.10.1.0.jar:1.10.1.0]
	at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityFilter.apply(OpenDistroSecurityFilter.java:138) [opendistro_security-1.10.1.0.jar:1.10.1.0]
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:177) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:155) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:83) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:409) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1274) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.getIndex(AbstractClient.java:1370) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.rest.action.admin.indices.RestGetIndicesAction.lambda$prepareRequest$0(RestGetIndicesAction.java:85) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:115) [elasticsearch-7.9.1.jar:7.9.1]
	at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityRestFilter$1.handleRequest(OpenDistroSecurityRestFilter.java:116) [opendistro_security-1.10.1.0.jar:1.10.1.0]
```

Im guessing its the `own_index` role which causes an attempt to resolve the username to an index as specified below
```
"index_patterns": [
    "${user_name}"
]
```

**Comment by Jon-AtAWS** [comment]
Hi @robmartin-scibite,

Sorry for the delay. I can't tell from your report whether this is a security issue or a query issue. Would you please re-ask your question in one of these forums?

Query: https://discuss.opendistrocommunity.dev/c/general-elasticsearch/10
Security: https://discuss.opendistrocommunity.dev/c/security/3

Thanks,

Jon
